"""add due_date and priority to tasks

Revision ID: b494101798a8
Revises: ae096670d8d9
Create Date: 2026-04-21 00:23:48.250511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b494101798a8'
down_revision: Union[str, Sequence[str], None] = 'ae096670d8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
